apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-devops-toolkit-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: "2.9.9"
        ingress:
          host: "pr-devops-toolkit-2.34.139.2.87.nip.io"
      version: v3
  destination:
    namespace: pr-devops-toolkit-2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
